# generated by datamodel-codegen:
#   filename:  schemas.json
#   timestamp: 2026-05-04T16:48:41+00:00

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, EmailStr, Field, RootModel


class DentalPMSSchemas(RootModel[Any]):
    root: Any = Field(..., title='DentalPMSSchemas')


class Features(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    eligibility_verification: bool | None = False
    copay_estimation: bool | None = False
    claims_submission: bool | None = False


class Practice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    name: str = Field(..., max_length=255, min_length=1)
    timezone: str = Field(..., min_length=1)
    phone: str | None = Field(None, max_length=20)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    features: Features | None = Field({}, validate_default=True)
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreatePractice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    timezone: str = Field(..., min_length=1)
    phone: str | None = Field(None, max_length=20)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    features: Features | None = Field({}, validate_default=True)


class Role(StrEnum):
    dentist = 'dentist'
    hygienist = 'hygienist'
    assistant = 'assistant'


class Provider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    npi: str = Field(..., max_length=10, min_length=10)
    role: Role
    is_active: bool | None = Field(True, alias='isActive')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateProvider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID = Field(..., alias='practiceId')
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    npi: str = Field(..., max_length=10, min_length=10)
    role: Role
    is_active: bool | None = Field(True, alias='isActive')


class Operatory(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    name: str = Field(..., max_length=100, min_length=1)
    is_active: bool | None = Field(True, alias='isActive')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateOperatory(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID = Field(..., alias='practiceId')
    name: str = Field(..., max_length=100, min_length=1)
    is_active: bool | None = Field(True, alias='isActive')


class Sex(StrEnum):
    male = 'male'
    female = 'female'
    other = 'other'
    unknown = 'unknown'


class MaritalStatus(StrEnum):
    single = 'single'
    married = 'married'
    divorced = 'divorced'
    widowed = 'widowed'
    separated = 'separated'
    domestic_partner = 'domestic_partner'
    other = 'other'


class Patient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    date_of_birth: date = Field(..., alias='dateOfBirth')
    sex: Sex | None = None
    marital_status: MaritalStatus | None = Field(None, alias='maritalStatus')
    last_xray_date: date | None = Field(None, alias='lastXrayDate')
    phone: str | None = Field(None, max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn: str | None = Field(None, pattern='^\\d{4}$|^\\d{9}$')
    emergency_contact_name: str | None = Field(None, alias='emergencyContactName', max_length=200)
    emergency_contact_phone: str | None = Field(None, alias='emergencyContactPhone', max_length=20)
    occupation: str | None = Field(None, max_length=200)
    employer: str | None = Field(None, max_length=200)
    referral_source: str | None = Field(None, alias='referralSource', max_length=200)
    allergies: list[str] | None = []
    medical_alerts: list[str] | None = Field([], alias='medicalAlerts')
    medications: list[str] | None = []
    dental_symptoms: list[str] | None = Field([], alias='dentalSymptoms')
    last_dental_visit: str | None = Field(None, alias='lastDentalVisit', max_length=500)
    previous_dentist: str | None = Field(None, alias='previousDentist', max_length=200)
    doctor_notes: str | None = Field(None, alias='doctorNotes', max_length=5000)
    sms_opt_out: bool | None = Field(False, alias='smsOptOut')
    deleted_at: AwareDatetime | None = Field(None, alias='deletedAt')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreatePatient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID | None = Field(None, alias='practiceId')
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    date_of_birth: date = Field(..., alias='dateOfBirth')
    sex: Sex | None = None
    marital_status: MaritalStatus | None = Field(None, alias='maritalStatus')
    last_xray_date: date | None = Field(None, alias='lastXrayDate')
    phone: str | None = Field(None, max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn: str | None = Field(None, pattern='^\\d{4}$|^\\d{9}$')
    emergency_contact_name: str | None = Field(None, alias='emergencyContactName', max_length=200)
    emergency_contact_phone: str | None = Field(None, alias='emergencyContactPhone', max_length=20)
    occupation: str | None = Field(None, max_length=200)
    employer: str | None = Field(None, max_length=200)
    referral_source: str | None = Field(None, alias='referralSource', max_length=200)
    allergies: list[str] | None = []
    medical_alerts: list[str] | None = Field([], alias='medicalAlerts')
    medications: list[str] | None = []
    dental_symptoms: list[str] | None = Field([], alias='dentalSymptoms')
    last_dental_visit: str | None = Field(None, alias='lastDentalVisit', max_length=500)
    previous_dentist: str | None = Field(None, alias='previousDentist', max_length=200)
    doctor_notes: str | None = Field(None, alias='doctorNotes', max_length=5000)
    sms_opt_out: bool | None = Field(False, alias='smsOptOut')


class UpdatePatient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID | None = Field(None, alias='practiceId')
    first_name: str | None = Field(None, alias='firstName', max_length=100, min_length=1)
    last_name: str | None = Field(None, alias='lastName', max_length=100, min_length=1)
    date_of_birth: date | None = Field(None, alias='dateOfBirth')
    sex: Sex | None = None
    marital_status: MaritalStatus | None = Field(None, alias='maritalStatus')
    last_xray_date: date | None = Field(None, alias='lastXrayDate')
    phone: str | None = Field(None, max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn: str | None = Field(None, pattern='^\\d{4}$|^\\d{9}$')
    emergency_contact_name: str | None = Field(None, alias='emergencyContactName', max_length=200)
    emergency_contact_phone: str | None = Field(None, alias='emergencyContactPhone', max_length=20)
    occupation: str | None = Field(None, max_length=200)
    employer: str | None = Field(None, max_length=200)
    referral_source: str | None = Field(None, alias='referralSource', max_length=200)
    allergies: list[str] | None = []
    medical_alerts: list[str] | None = Field([], alias='medicalAlerts')
    medications: list[str] | None = []
    dental_symptoms: list[str] | None = Field([], alias='dentalSymptoms')
    last_dental_visit: str | None = Field(None, alias='lastDentalVisit', max_length=500)
    previous_dentist: str | None = Field(None, alias='previousDentist', max_length=200)
    doctor_notes: str | None = Field(None, alias='doctorNotes', max_length=5000)
    sms_opt_out: bool | None = Field(False, alias='smsOptOut')


class PatientSearchQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    q: str | None = Field(None, min_length=1)
    page: int | None = Field(1, ge=1)
    page_size: int | None = Field(20, alias='pageSize', ge=1, le=100)


class PaginationQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: int | None = Field(1, ge=1)
    page_size: int | None = Field(20, alias='pageSize', ge=1, le=100)


class PaginationMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: int
    page_size: int = Field(..., alias='pageSize')
    total: int
    total_pages: int = Field(..., alias='totalPages')


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    message: str
    details: dict[str, Any] | None = None


class ApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Error


class IntakeFormTokenInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_name: str = Field(..., alias='practiceName')
    patient_first_name: str = Field(..., alias='patientFirstName')


class RelationshipToInsured(StrEnum):
    self = 'self'
    spouse = 'spouse'
    child = 'child'
    other = 'other'


class SubmitIntakeForm(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    date_of_birth: date = Field(..., alias='dateOfBirth')
    sex: Sex | None = None
    phone: str = Field(..., max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn: str | None = Field(None, pattern='^\\d{4}$|^\\d{9}$')
    marital_status: MaritalStatus | None = Field(None, alias='maritalStatus')
    emergency_contact_name: str | None = Field(None, alias='emergencyContactName', max_length=200)
    emergency_contact_phone: str | None = Field(None, alias='emergencyContactPhone', max_length=20)
    occupation: str | None = Field(None, max_length=200)
    employer: str | None = Field(None, max_length=200)
    referral_source: str | None = Field(None, alias='referralSource', max_length=200)
    medical_conditions: list[str] | None = Field([], alias='medicalConditions')
    medications: list[str] | None = []
    allergies: list[str] | None = []
    dental_symptoms: list[str] | None = Field([], alias='dentalSymptoms')
    last_dental_visit: str | None = Field(None, alias='lastDentalVisit')
    last_xray_date: str | None = Field(None, alias='lastXrayDate')
    previous_dentist: str | None = Field(None, alias='previousDentist')
    chief_complaint: str | None = Field(None, alias='chiefComplaint')
    insurance_carrier: str | None = Field(None, alias='insuranceCarrier')
    insurance_member_id: str | None = Field(None, alias='insuranceMemberId')
    insurance_group_number: str | None = Field(None, alias='insuranceGroupNumber')
    insurance_holder_name: str | None = Field(None, alias='insuranceHolderName')
    insurance_holder_dob: str | None = Field(None, alias='insuranceHolderDob')
    relationship_to_insured: RelationshipToInsured | None = Field(None, alias='relationshipToInsured')
    hipaa_consent_accepted: bool = Field(..., alias='hipaaConsentAccepted')
    hipaa_consent_timestamp: AwareDatetime = Field(..., alias='hipaaConsentTimestamp')
    hipaa_consent_signature: str = Field(..., alias='hipaaConsentSignature', min_length=1)
    sms_opt_in: bool = Field(..., alias='smsOptIn')


class SendIntakeForm(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    patient_id: UUID = Field(..., alias='patientId')


class SendIntakeFormResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    intake_form_id: UUID = Field(..., alias='intakeFormId')
    expires_at: AwareDatetime = Field(..., alias='expiresAt')
    form_url: AnyUrl = Field(..., alias='formUrl')


class Status(StrEnum):
    pending = 'pending'
    completed = 'completed'
    expired = 'expired'


class IntakeFormSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    patient_id: UUID = Field(..., alias='patientId')
    status: Status
    expires_at: AwareDatetime = Field(..., alias='expiresAt')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    created_by: UUID = Field(..., alias='createdBy')


class Responses(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    date_of_birth: date = Field(..., alias='dateOfBirth')
    sex: Sex | None = None
    phone: str = Field(..., max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn: str | None = Field(None, pattern='^\\d{4}$|^\\d{9}$')
    marital_status: MaritalStatus | None = Field(None, alias='maritalStatus')
    emergency_contact_name: str | None = Field(None, alias='emergencyContactName', max_length=200)
    emergency_contact_phone: str | None = Field(None, alias='emergencyContactPhone', max_length=20)
    occupation: str | None = Field(None, max_length=200)
    employer: str | None = Field(None, max_length=200)
    referral_source: str | None = Field(None, alias='referralSource', max_length=200)
    medical_conditions: list[str] | None = Field([], alias='medicalConditions')
    medications: list[str] | None = []
    allergies: list[str] | None = []
    dental_symptoms: list[str] | None = Field([], alias='dentalSymptoms')
    last_dental_visit: str | None = Field(None, alias='lastDentalVisit')
    last_xray_date: str | None = Field(None, alias='lastXrayDate')
    previous_dentist: str | None = Field(None, alias='previousDentist')
    chief_complaint: str | None = Field(None, alias='chiefComplaint')
    insurance_carrier: str | None = Field(None, alias='insuranceCarrier')
    insurance_member_id: str | None = Field(None, alias='insuranceMemberId')
    insurance_group_number: str | None = Field(None, alias='insuranceGroupNumber')
    insurance_holder_name: str | None = Field(None, alias='insuranceHolderName')
    insurance_holder_dob: str | None = Field(None, alias='insuranceHolderDob')
    relationship_to_insured: RelationshipToInsured | None = Field(None, alias='relationshipToInsured')
    hipaa_consent_accepted: bool = Field(..., alias='hipaaConsentAccepted')
    hipaa_consent_timestamp: AwareDatetime = Field(..., alias='hipaaConsentTimestamp')
    hipaa_consent_signature: str = Field(..., alias='hipaaConsentSignature', min_length=1)
    sms_opt_in: bool = Field(..., alias='smsOptIn')


class IntakeFormDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    patient_id: UUID = Field(..., alias='patientId')
    status: Status
    expires_at: AwareDatetime = Field(..., alias='expiresAt')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    created_by: UUID = Field(..., alias='createdBy')
    responses: Responses | None


class Priority(StrEnum):
    primary = 'primary'
    secondary = 'secondary'


class Insurance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    patient_id: UUID = Field(..., alias='patientId')
    practice_id: UUID = Field(..., alias='practiceId')
    insurance_plan_id: UUID | None = Field(None, alias='insurancePlanId')
    priority: Priority | None = 'primary'
    carrier: str = Field(..., max_length=255, min_length=1)
    member_id: str | None = Field(None, alias='memberId', max_length=100)
    group_number: str | None = Field(None, alias='groupNumber', max_length=100)
    relationship_to_insured: RelationshipToInsured | None = Field('self', alias='relationshipToInsured')
    insured_first_name: str | None = Field(None, alias='insuredFirstName', max_length=100)
    insured_last_name: str | None = Field(None, alias='insuredLastName', max_length=100)
    insured_date_of_birth: date | None = Field(None, alias='insuredDateOfBirth')
    is_active: bool | None = Field(True, alias='isActive')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateInsurance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    insurance_plan_id: UUID | None = Field(None, alias='insurancePlanId')
    priority: Priority | None = 'primary'
    carrier: str = Field(..., max_length=255, min_length=1)
    member_id: str | None = Field(None, alias='memberId', max_length=100)
    group_number: str | None = Field(None, alias='groupNumber', max_length=100)
    relationship_to_insured: RelationshipToInsured | None = Field('self', alias='relationshipToInsured')
    insured_first_name: str | None = Field(None, alias='insuredFirstName', max_length=100)
    insured_last_name: str | None = Field(None, alias='insuredLastName', max_length=100)
    insured_date_of_birth: date | None = Field(None, alias='insuredDateOfBirth')


class UpdateInsurance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    insurance_plan_id: UUID | None = Field(None, alias='insurancePlanId')
    priority: Priority | None = 'primary'
    carrier: str | None = Field(None, max_length=255, min_length=1)
    member_id: str | None = Field(None, alias='memberId', max_length=100)
    group_number: str | None = Field(None, alias='groupNumber', max_length=100)
    relationship_to_insured: RelationshipToInsured | None = Field('self', alias='relationshipToInsured')
    insured_first_name: str | None = Field(None, alias='insuredFirstName', max_length=100)
    insured_last_name: str | None = Field(None, alias='insuredLastName', max_length=100)
    insured_date_of_birth: date | None = Field(None, alias='insuredDateOfBirth')


class InsurancePlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    carrier_name: str = Field(..., alias='carrierName', max_length=255, min_length=1)
    payer_id: str = Field(..., alias='payerId', max_length=50, min_length=1)
    group_number: str | None = Field(None, alias='groupNumber', max_length=100)
    is_in_network: bool | None = Field(True, alias='isInNetwork')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateInsurancePlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    carrier_name: str = Field(..., alias='carrierName', max_length=255, min_length=1)
    payer_id: str = Field(..., alias='payerId', max_length=50, min_length=1)
    group_number: str | None = Field(None, alias='groupNumber', max_length=100)
    is_in_network: bool | None = Field(True, alias='isInNetwork')


class UpdateInsurancePlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    carrier_name: str | None = Field(None, alias='carrierName', max_length=255, min_length=1)
    payer_id: str | None = Field(None, alias='payerId', max_length=50, min_length=1)
    group_number: str | None = Field(None, alias='groupNumber', max_length=100)
    is_in_network: bool | None = Field(True, alias='isInNetwork')


class ReminderSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reminder_hours: list[int] = Field(..., alias='reminderHours')


class UpdateReminderSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reminder_hours: list[int] = Field(..., alias='reminderHours')


class DefaultCdtCode(RootModel[str]):
    root: str = Field(..., max_length=10)


class AppointmentType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    name: str = Field(..., max_length=255, min_length=1)
    duration_minutes: int = Field(..., alias='durationMinutes', ge=5, le=480)
    color: str | None = Field('#5B8DEF', pattern='^#[0-9A-Fa-f]{6}$')
    default_cdt_codes: list[DefaultCdtCode] | None = Field([], alias='defaultCdtCodes', validate_default=True)
    is_active: bool | None = Field(True, alias='isActive')
    display_order: int | None = Field(0, alias='displayOrder')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateAppointmentType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID | None = Field(None, alias='practiceId')
    name: str = Field(..., max_length=255, min_length=1)
    duration_minutes: int = Field(..., alias='durationMinutes', ge=5, le=480)
    color: str | None = Field('#5B8DEF', pattern='^#[0-9A-Fa-f]{6}$')
    default_cdt_codes: list[DefaultCdtCode] | None = Field([], alias='defaultCdtCodes', validate_default=True)
    is_active: bool | None = Field(True, alias='isActive')
    display_order: int | None = Field(0, alias='displayOrder')


class UpdateAppointmentType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID | None = Field(None, alias='practiceId')
    name: str | None = Field(None, max_length=255, min_length=1)
    duration_minutes: int | None = Field(None, alias='durationMinutes', ge=5, le=480)
    color: str | None = Field('#5B8DEF', pattern='^#[0-9A-Fa-f]{6}$')
    default_cdt_codes: list[DefaultCdtCode] | None = Field([], alias='defaultCdtCodes', validate_default=True)
    is_active: bool | None = Field(True, alias='isActive')
    display_order: int | None = Field(0, alias='displayOrder')


class Status2(StrEnum):
    scheduled = 'scheduled'
    confirmed = 'confirmed'
    checked_in = 'checked_in'
    in_chair = 'in_chair'
    completed = 'completed'
    cancelled = 'cancelled'
    no_show = 'no_show'


class ReminderSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sms_status: str | None = Field(None, alias='smsStatus')
    email_status: str | None = Field(None, alias='emailStatus')
    patient_sms_opted_out: bool | None = Field(False, alias='patientSmsOptedOut')


class Appointment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    patient_id: UUID | None = Field(None, alias='patientId')
    provider_id: UUID | None = Field(None, alias='providerId')
    operatory_id: UUID | None = Field(None, alias='operatoryId')
    appointment_type_id: UUID | None = Field(None, alias='appointmentTypeId')
    start_time: AwareDatetime = Field(..., alias='startTime')
    end_time: AwareDatetime = Field(..., alias='endTime')
    status: Status2
    notes: str | None = Field(None, max_length=5000)
    cancellation_reason: str | None = Field(None, alias='cancellationReason', max_length=1000)
    patient_name: str | None = Field(None, alias='patientName')
    provider_name: str | None = Field(None, alias='providerName')
    operatory_name: str | None = Field(None, alias='operatoryName')
    appointment_type_name: str | None = Field(None, alias='appointmentTypeName')
    appointment_type_color: str | None = Field(None, alias='appointmentTypeColor')
    reminder_summary: ReminderSummary | None = Field(None, alias='reminderSummary')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateAppointment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    patient_id: UUID = Field(..., alias='patientId')
    provider_id: UUID = Field(..., alias='providerId')
    operatory_id: UUID = Field(..., alias='operatoryId')
    appointment_type_id: UUID | None = Field(None, alias='appointmentTypeId')
    start_time: AwareDatetime = Field(..., alias='startTime')
    end_time: AwareDatetime = Field(..., alias='endTime')
    notes: str | None = Field(None, max_length=5000)


class UpdateAppointment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    patient_id: UUID | None = Field(None, alias='patientId')
    provider_id: UUID | None = Field(None, alias='providerId')
    operatory_id: UUID | None = Field(None, alias='operatoryId')
    appointment_type_id: UUID | None = Field(None, alias='appointmentTypeId')
    start_time: AwareDatetime | None = Field(None, alias='startTime')
    end_time: AwareDatetime | None = Field(None, alias='endTime')
    status: Status2 | None = None
    notes: str | None = Field(None, max_length=5000)
    cancellation_reason: str | None = Field(None, alias='cancellationReason', max_length=1000)


class CancelAppointment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cancellation_reason: str | None = Field(None, alias='cancellationReason', max_length=1000)


class ProviderType(StrEnum):
    dentist = 'dentist'
    hygienist = 'hygienist'
    specialist = 'specialist'
    other = 'other'


class ProviderResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    full_name: str = Field(..., alias='fullName', max_length=255, min_length=1)
    npi: str = Field(..., max_length=10, min_length=10, pattern='^\\d{10}$')
    provider_type: ProviderType = Field(..., alias='providerType')
    license_number: str | None = Field(None, alias='licenseNumber', max_length=50)
    specialty: str | None = Field(None, max_length=255)
    color: str | None = Field('#4F86C6', pattern='^#[0-9A-Fa-f]{6}$')
    is_active: bool | None = Field(True, alias='isActive')
    display_order: int | None = Field(0, alias='displayOrder')
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateProviderBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    full_name: str = Field(..., alias='fullName', max_length=255, min_length=1)
    npi: str = Field(..., max_length=10, min_length=10, pattern='^\\d{10}$')
    provider_type: ProviderType = Field(..., alias='providerType')
    license_number: str | None = Field(None, alias='licenseNumber', max_length=50)
    specialty: str | None = Field(None, max_length=255)
    color: str | None = Field('#4F86C6', pattern='^#[0-9A-Fa-f]{6}$')
    is_active: bool | None = Field(True, alias='isActive')
    display_order: int | None = Field(0, alias='displayOrder')


class UpdateProviderBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    full_name: str | None = Field(None, alias='fullName', max_length=255, min_length=1)
    npi: str | None = Field(None, max_length=10, min_length=10, pattern='^\\d{10}$')
    provider_type: ProviderType | None = Field(None, alias='providerType')
    license_number: str | None = Field(None, alias='licenseNumber', max_length=50)
    specialty: str | None = Field(None, max_length=255)
    color: str | None = Field('#4F86C6', pattern='^#[0-9A-Fa-f]{6}$')
    is_active: bool | None = Field(True, alias='isActive')
    display_order: int | None = Field(0, alias='displayOrder')


class OperatoryResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=100, min_length=1)
    color: str | None = Field('#7BC67E', pattern='^#[0-9A-Fa-f]{6}$')
    is_active: bool | None = Field(True, alias='isActive')
    display_order: int | None = Field(0, alias='displayOrder')
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateOperatoryBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=100, min_length=1)
    color: str | None = Field('#7BC67E', pattern='^#[0-9A-Fa-f]{6}$')
    is_active: bool | None = Field(True, alias='isActive')
    display_order: int | None = Field(0, alias='displayOrder')


class UpdateOperatoryBody(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = Field(None, max_length=100, min_length=1)
    color: str | None = Field('#7BC67E', pattern='^#[0-9A-Fa-f]{6}$')
    is_active: bool | None = Field(True, alias='isActive')
    display_order: int | None = Field(0, alias='displayOrder')


class AppointmentReminderRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    reminder_type: str = Field(..., alias='reminderType')
    hours_before: int = Field(..., alias='hoursBefore')
    send_at: AwareDatetime = Field(..., alias='sendAt')
    status: str
    sent_at: AwareDatetime | None = Field(None, alias='sentAt')
    failed_at: AwareDatetime | None = Field(None, alias='failedAt')
    failure_reason: str | None = Field(None, alias='failureReason')
    response_received: str | None = Field(None, alias='responseReceived')
    responded_at: AwareDatetime | None = Field(None, alias='respondedAt')


class Status4(StrEnum):
    pending = 'pending'
    verified = 'verified'
    failed = 'failed'
    not_supported = 'not_supported'


class Trigger(StrEnum):
    manual = 'manual'
    pre_appointment_batch = 'pre_appointment_batch'


class CoverageStatus(StrEnum):
    active = 'active'
    inactive = 'inactive'
    unknown = 'unknown'


class EligibilityCheck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    patient_id: UUID = Field(..., alias='patientId')
    patient_insurance_id: UUID = Field(..., alias='patientInsuranceId')
    appointment_id: UUID | None = Field(None, alias='appointmentId')
    idempotency_key: str = Field(..., alias='idempotencyKey')
    status: Status4
    trigger: Trigger
    clearinghouse: str
    payer_id_used: str = Field(..., alias='payerIdUsed')
    payer_name: str | None = Field(None, alias='payerName')
    failure_reason: str | None = Field(None, alias='failureReason')
    coverage_status: CoverageStatus | None = Field(None, alias='coverageStatus')
    coverage_start_date: date | None = Field(None, alias='coverageStartDate')
    coverage_end_date: date | None = Field(None, alias='coverageEndDate')
    deductible_individual: float | None = Field(None, alias='deductibleIndividual')
    deductible_individual_met: float | None = Field(None, alias='deductibleIndividualMet')
    deductible_family: float | None = Field(None, alias='deductibleFamily')
    deductible_family_met: float | None = Field(None, alias='deductibleFamilyMet')
    oop_max_individual: float | None = Field(None, alias='oopMaxIndividual')
    oop_max_individual_met: float | None = Field(None, alias='oopMaxIndividualMet')
    annual_max_individual: float | None = Field(None, alias='annualMaxIndividual')
    annual_max_individual_used: float | None = Field(None, alias='annualMaxIndividualUsed')
    annual_max_individual_remaining: float | None = Field(None, alias='annualMaxIndividualRemaining')
    coinsurance_preventive: float | None = Field(None, alias='coinsurancePreventive')
    coinsurance_basic: float | None = Field(None, alias='coinsuranceBasic')
    coinsurance_major: float | None = Field(None, alias='coinsuranceMajor')
    coinsurance_ortho: float | None = Field(None, alias='coinsuranceOrtho')
    waiting_period_basic_months: int | None = Field(None, alias='waitingPeriodBasicMonths')
    waiting_period_major_months: int | None = Field(None, alias='waitingPeriodMajorMonths')
    waiting_period_ortho_months: int | None = Field(None, alias='waitingPeriodOrthoMonths')
    frequency_limits: dict[str, Any] | None = Field(None, alias='frequencyLimits')
    requested_at: AwareDatetime = Field(..., alias='requestedAt')
    verified_at: AwareDatetime | None = Field(None, alias='verifiedAt')
    failed_at: AwareDatetime | None = Field(None, alias='failedAt')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateEligibilityCheck(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    patient_insurance_id: UUID = Field(..., alias='patientInsuranceId')
    appointment_id: UUID | None = Field(None, alias='appointmentId')


class AllergyEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    severity: str | None = Field(None, max_length=50)
    reaction: str | None = Field(None, max_length=500)


class MedicationEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    dose: str | None = Field(None, max_length=100)
    frequency: str | None = Field(None, max_length=100)


class ConditionEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    icd10_hint: str | None = Field(None, alias='icd10Hint', max_length=20)
    notes: str | None = Field(None, max_length=1000)


class MedicalFlags(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag_blood_thinners: bool | None = Field(False, alias='flagBloodThinners')
    flag_bisphosphonates: bool | None = Field(False, alias='flagBisphosphonates')
    flag_heart_condition: bool | None = Field(False, alias='flagHeartCondition')
    flag_diabetes: bool | None = Field(False, alias='flagDiabetes')
    flag_pacemaker: bool | None = Field(False, alias='flagPacemaker')
    flag_latex_allergy: bool | None = Field(False, alias='flagLatexAllergy')


class Allergy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    severity: str | None = Field(None, max_length=50)
    reaction: str | None = Field(None, max_length=500)


class Medication(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    dose: str | None = Field(None, max_length=100)
    frequency: str | None = Field(None, max_length=100)


class Condition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    icd10_hint: str | None = Field(None, alias='icd10Hint', max_length=20)
    notes: str | None = Field(None, max_length=1000)


class Flags(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    flag_blood_thinners: bool | None = Field(False, alias='flagBloodThinners')
    flag_bisphosphonates: bool | None = Field(False, alias='flagBisphosphonates')
    flag_heart_condition: bool | None = Field(False, alias='flagHeartCondition')
    flag_diabetes: bool | None = Field(False, alias='flagDiabetes')
    flag_pacemaker: bool | None = Field(False, alias='flagPacemaker')
    flag_latex_allergy: bool | None = Field(False, alias='flagLatexAllergy')


class MedicalHistoryVersion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    patient_id: UUID = Field(..., alias='patientId')
    version_number: int = Field(..., alias='versionNumber', ge=1)
    recorded_by: UUID = Field(..., alias='recordedBy')
    recorded_at: AwareDatetime = Field(..., alias='recordedAt')
    allergies: list[Allergy]
    medications: list[Medication]
    conditions: list[Condition]
    flags: Flags
    additional_notes: str | None = Field(None, alias='additionalNotes', max_length=5000)
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class MedicalHistoryVersionSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    version_number: int = Field(..., alias='versionNumber', ge=1)
    recorded_by: UUID = Field(..., alias='recordedBy')
    recorded_at: AwareDatetime = Field(..., alias='recordedAt')
    allergy_count: int = Field(..., alias='allergyCount', ge=0)
    medication_count: int = Field(..., alias='medicationCount', ge=0)
    condition_count: int = Field(..., alias='conditionCount', ge=0)
    flags: Flags


class CreateMedicalHistory(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allergies: list[Allergy] | None = Field([], validate_default=True)
    medications: list[Medication] | None = Field([], validate_default=True)
    conditions: list[Condition] | None = Field([], validate_default=True)
    flags: Flags | None = None
    additional_notes: str | None = Field(None, alias='additionalNotes', max_length=5000)


class Item(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    version_number: int = Field(..., alias='versionNumber', ge=1)
    recorded_by: UUID = Field(..., alias='recordedBy')
    recorded_at: AwareDatetime = Field(..., alias='recordedAt')
    allergy_count: int = Field(..., alias='allergyCount', ge=0)
    medication_count: int = Field(..., alias='medicationCount', ge=0)
    condition_count: int = Field(..., alias='conditionCount', ge=0)
    flags: Flags


class MedicalHistoryHistoryResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Item]
    total: int
    page: int
    page_size: int = Field(..., alias='pageSize')


class PatientTolerance(StrEnum):
    excellent = 'excellent'
    good = 'good'
    fair = 'fair'
    poor = 'poor'


class TemplateType(StrEnum):
    exam = 'exam'
    prophy = 'prophy'
    extraction = 'extraction'
    crown_prep = 'crown_prep'
    crown_seat = 'crown_seat'
    root_canal = 'root_canal'
    filling = 'filling'
    srp = 'srp'
    other = 'other'


class ClinicalNote(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    patient_id: UUID = Field(..., alias='patientId')
    appointment_id: UUID | None = Field(..., alias='appointmentId')
    provider_id: UUID = Field(..., alias='providerId')
    visit_date: date = Field(..., alias='visitDate')
    chief_complaint: str | None = Field(..., alias='chiefComplaint')
    anesthesia: str | None
    patient_tolerance: PatientTolerance | None = Field(..., alias='patientTolerance')
    complications: str | None
    treatment_rendered: str = Field(..., alias='treatmentRendered', min_length=1)
    next_visit_plan: str | None = Field(..., alias='nextVisitPlan')
    notes: str | None
    template_type: TemplateType | None = Field(..., alias='templateType')
    is_signed: bool = Field(..., alias='isSigned')
    signed_at: AwareDatetime | None = Field(..., alias='signedAt')
    signed_by_provider_id: UUID | None = Field(..., alias='signedByProviderId')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class ClinicalNoteSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    patient_id: UUID = Field(..., alias='patientId')
    provider_id: UUID = Field(..., alias='providerId')
    appointment_id: UUID | None = Field(..., alias='appointmentId')
    visit_date: date = Field(..., alias='visitDate')
    treatment_rendered: str = Field(..., alias='treatmentRendered', min_length=1)
    template_type: TemplateType | None = Field(..., alias='templateType')
    is_signed: bool = Field(..., alias='isSigned')
    signed_at: AwareDatetime | None = Field(..., alias='signedAt')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateClinicalNote(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    appointment_id: UUID | None = Field(None, alias='appointmentId')
    provider_id: UUID = Field(..., alias='providerId')
    visit_date: date = Field(..., alias='visitDate')
    chief_complaint: str | None = Field(None, alias='chiefComplaint')
    anesthesia: str | None = None
    patient_tolerance: PatientTolerance | None = Field(None, alias='patientTolerance')
    complications: str | None = None
    treatment_rendered: str = Field(..., alias='treatmentRendered', min_length=1)
    next_visit_plan: str | None = Field(None, alias='nextVisitPlan')
    notes: str | None = None
    template_type: TemplateType | None = Field(None, alias='templateType')


class UpdateClinicalNote(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chief_complaint: str | None = Field(None, alias='chiefComplaint')
    anesthesia: str | None = None
    patient_tolerance: PatientTolerance | None = Field(None, alias='patientTolerance')
    complications: str | None = None
    treatment_rendered: str | None = Field(None, alias='treatmentRendered', min_length=1)
    next_visit_plan: str | None = Field(None, alias='nextVisitPlan')
    notes: str | None = None
    template_type: TemplateType | None = Field(None, alias='templateType')


class Item1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    patient_id: UUID = Field(..., alias='patientId')
    provider_id: UUID = Field(..., alias='providerId')
    appointment_id: UUID | None = Field(..., alias='appointmentId')
    visit_date: date = Field(..., alias='visitDate')
    treatment_rendered: str = Field(..., alias='treatmentRendered', min_length=1)
    template_type: TemplateType | None = Field(..., alias='templateType')
    is_signed: bool = Field(..., alias='isSigned')
    signed_at: AwareDatetime | None = Field(..., alias='signedAt')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class ClinicalNoteListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Item1]
    next_cursor: str | None = Field(..., alias='nextCursor')
    has_more: bool = Field(..., alias='hasMore')


class ConditionType(StrEnum):
    existing_restoration = 'existing_restoration'
    missing = 'missing'
    implant = 'implant'
    crown = 'crown'
    bridge_pontic = 'bridge_pontic'
    bridge_abutment = 'bridge_abutment'
    root_canal = 'root_canal'
    decay = 'decay'
    fracture = 'fracture'
    watch = 'watch'
    other = 'other'


class NotationSystem(StrEnum):
    universal = 'universal'
    fdi = 'fdi'


class ToothConditionStatus(StrEnum):
    existing = 'existing'
    treatment_planned = 'treatment_planned'
    completed_today = 'completed_today'


class Status5(StrEnum):
    existing = 'existing'
    treatment_planned = 'treatment_planned'
    completed_today = 'completed_today'


class ToothCondition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    patient_id: UUID = Field(..., alias='patientId')
    tooth_number: str = Field(..., alias='toothNumber', min_length=1)
    notation_system: NotationSystem = Field(..., alias='notationSystem')
    condition_type: ConditionType = Field(..., alias='conditionType')
    surface: str | None
    material: str | None
    notes: str | None
    status: Status5
    recorded_at: date = Field(..., alias='recordedAt')
    recorded_by: UUID = Field(..., alias='recordedBy')
    appointment_id: UUID | None = Field(..., alias='appointmentId')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateToothCondition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tooth_number: str = Field(..., alias='toothNumber', min_length=1)
    notation_system: NotationSystem | None = Field(None, alias='notationSystem')
    condition_type: ConditionType = Field(..., alias='conditionType')
    surface: str | None = None
    material: str | None = None
    notes: str | None = None
    status: Status5 | None = None
    recorded_at: date = Field(..., alias='recordedAt')
    recorded_by: UUID = Field(..., alias='recordedBy')
    appointment_id: UUID | None = Field(None, alias='appointmentId')


class UpdateToothCondition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status5 | None = None
    surface: str | None = None
    material: str | None = None
    notes: str | None = None


class Condition2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    patient_id: UUID = Field(..., alias='patientId')
    tooth_number: str = Field(..., alias='toothNumber', min_length=1)
    notation_system: NotationSystem = Field(..., alias='notationSystem')
    condition_type: ConditionType = Field(..., alias='conditionType')
    surface: str | None
    material: str | None
    notes: str | None
    status: Status5
    recorded_at: date = Field(..., alias='recordedAt')
    recorded_by: UUID = Field(..., alias='recordedBy')
    appointment_id: UUID | None = Field(..., alias='appointmentId')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class ToothChartResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    conditions: list[Condition2]


class TreatmentPlanStatus(StrEnum):
    proposed = 'proposed'
    accepted = 'accepted'
    in_progress = 'in_progress'
    completed = 'completed'
    refused = 'refused'
    superseded = 'superseded'


class TreatmentPlanItemStatus(StrEnum):
    proposed = 'proposed'
    accepted = 'accepted'
    scheduled = 'scheduled'
    completed = 'completed'
    refused = 'refused'


class Status9(StrEnum):
    proposed = 'proposed'
    accepted = 'accepted'
    in_progress = 'in_progress'
    completed = 'completed'
    refused = 'refused'
    superseded = 'superseded'


class TreatmentPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    patient_id: UUID = Field(..., alias='patientId')
    name: str = Field(..., min_length=1)
    status: Status9
    presented_at: date | None = Field(..., alias='presentedAt')
    accepted_at: date | None = Field(..., alias='acceptedAt')
    completed_at: date | None = Field(..., alias='completedAt')
    notes: str | None
    created_by: UUID = Field(..., alias='createdBy')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class InsuranceEstCents(RootModel[int]):
    root: int = Field(..., ge=0)


class PatientEstCents(RootModel[int]):
    root: int = Field(..., ge=0)


class Status11(StrEnum):
    proposed = 'proposed'
    accepted = 'accepted'
    scheduled = 'scheduled'
    completed = 'completed'
    refused = 'refused'


class Item2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    treatment_plan_id: UUID = Field(..., alias='treatmentPlanId')
    patient_id: UUID = Field(..., alias='patientId')
    tooth_number: str | None = Field(..., alias='toothNumber')
    procedure_code: str = Field(..., alias='procedureCode', min_length=1)
    procedure_name: str = Field(..., alias='procedureName', min_length=1)
    surface: str | None
    fee_cents: int = Field(..., alias='feeCents', ge=0)
    insurance_est_cents: InsuranceEstCents | None = Field(..., alias='insuranceEstCents')
    patient_est_cents: PatientEstCents | None = Field(..., alias='patientEstCents')
    status: Status11
    priority: int = Field(..., gt=0)
    appointment_id: UUID | None = Field(..., alias='appointmentId')
    completed_appointment_id: UUID | None = Field(..., alias='completedAppointmentId')
    notes: str | None
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class TreatmentPlanDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    patient_id: UUID = Field(..., alias='patientId')
    name: str = Field(..., min_length=1)
    status: Status9
    presented_at: date | None = Field(..., alias='presentedAt')
    accepted_at: date | None = Field(..., alias='acceptedAt')
    completed_at: date | None = Field(..., alias='completedAt')
    notes: str | None
    created_by: UUID = Field(..., alias='createdBy')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')
    items: list[Item2]


class TreatmentPlanItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    treatment_plan_id: UUID = Field(..., alias='treatmentPlanId')
    patient_id: UUID = Field(..., alias='patientId')
    tooth_number: str | None = Field(..., alias='toothNumber')
    procedure_code: str = Field(..., alias='procedureCode', min_length=1)
    procedure_name: str = Field(..., alias='procedureName', min_length=1)
    surface: str | None
    fee_cents: int = Field(..., alias='feeCents', ge=0)
    insurance_est_cents: InsuranceEstCents | None = Field(..., alias='insuranceEstCents')
    patient_est_cents: PatientEstCents | None = Field(..., alias='patientEstCents')
    status: Status11
    priority: int = Field(..., gt=0)
    appointment_id: UUID | None = Field(..., alias='appointmentId')
    completed_appointment_id: UUID | None = Field(..., alias='completedAppointmentId')
    notes: str | None
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class Item3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tooth_number: str | None = Field(None, alias='toothNumber')
    procedure_code: str = Field(..., alias='procedureCode', min_length=1)
    procedure_name: str = Field(..., alias='procedureName', min_length=1)
    surface: str | None = None
    fee_cents: int = Field(..., alias='feeCents', ge=0)
    insurance_est_cents: int | None = Field(None, alias='insuranceEstCents', ge=0)
    patient_est_cents: int | None = Field(None, alias='patientEstCents', ge=0)
    priority: int | None = Field(None, gt=0)
    notes: str | None = None


class CreateTreatmentPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = Field(None, min_length=1)
    notes: str | None = None
    items: list[Item3] | None = None


class CreateTreatmentPlanItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tooth_number: str | None = Field(None, alias='toothNumber')
    procedure_code: str = Field(..., alias='procedureCode', min_length=1)
    procedure_name: str = Field(..., alias='procedureName', min_length=1)
    surface: str | None = None
    fee_cents: int = Field(..., alias='feeCents', ge=0)
    insurance_est_cents: int | None = Field(None, alias='insuranceEstCents', ge=0)
    patient_est_cents: int | None = Field(None, alias='patientEstCents', ge=0)
    priority: int | None = Field(None, gt=0)
    notes: str | None = None


class Status13(StrEnum):
    proposed = 'proposed'
    accepted = 'accepted'
    in_progress = 'in_progress'
    completed = 'completed'
    refused = 'refused'
    superseded = 'superseded'


class UpdateTreatmentPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str | None = Field(None, min_length=1)
    status: Status13 | None = None
    presented_at: date | None = Field(None, alias='presentedAt')
    notes: str | None = None


class Status14(StrEnum):
    proposed = 'proposed'
    accepted = 'accepted'
    scheduled = 'scheduled'
    completed = 'completed'
    refused = 'refused'


class UpdateTreatmentPlanItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status14 | None = None
    fee_cents: int | None = Field(None, alias='feeCents', ge=0)
    insurance_est_cents: int | None = Field(None, alias='insuranceEstCents', ge=0)
    patient_est_cents: int | None = Field(None, alias='patientEstCents', ge=0)
    appointment_id: UUID | None = Field(None, alias='appointmentId')
    completed_appointment_id: UUID | None = Field(None, alias='completedAppointmentId')
    priority: int | None = Field(None, gt=0)
    notes: str | None = None


class Status15(StrEnum):
    proposed = 'proposed'
    accepted = 'accepted'
    in_progress = 'in_progress'
    completed = 'completed'
    refused = 'refused'
    superseded = 'superseded'


class Item4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    patient_id: UUID = Field(..., alias='patientId')
    name: str = Field(..., min_length=1)
    status: Status15
    presented_at: date | None = Field(..., alias='presentedAt')
    accepted_at: date | None = Field(..., alias='acceptedAt')
    completed_at: date | None = Field(..., alias='completedAt')
    notes: str | None
    created_by: UUID = Field(..., alias='createdBy')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class TreatmentPlanListResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: list[Item4]
    next_cursor: str | None = Field(..., alias='nextCursor')
    has_more: bool = Field(..., alias='hasMore')


class OpenPlanQueueItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    plan_id: UUID = Field(..., alias='planId')
    plan_name: str = Field(..., alias='planName')
    patient_id: UUID = Field(..., alias='patientId')
    patient_name: str = Field(..., alias='patientName')
    pending_item_count: int = Field(..., alias='pendingItemCount', ge=0)
    days_since_acceptance: int = Field(..., alias='daysSinceAcceptance', ge=0)
    accepted_at: date | None = Field(..., alias='acceptedAt')
