# generated by datamodel-codegen:
#   filename:  schemas.json
#   timestamp: 2026-04-05T01:30:40+00:00

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field, RootModel


class DentalPMSSchemas(RootModel[Any]):
    root: Any = Field(..., title='DentalPMSSchemas')


class Features(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    eligibility_verification: bool | None = False
    copay_estimation: bool | None = False
    claims_submission: bool | None = False


class Practice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    name: str = Field(..., max_length=255, min_length=1)
    timezone: str = Field(..., min_length=1)
    phone: str | None = Field(None, max_length=20)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    features: Features | None = Field({}, validate_default=True)
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreatePractice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    timezone: str = Field(..., min_length=1)
    phone: str | None = Field(None, max_length=20)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    features: Features | None = Field({}, validate_default=True)


class Role(StrEnum):
    dentist = 'dentist'
    hygienist = 'hygienist'
    assistant = 'assistant'


class Provider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    npi: str = Field(..., max_length=10, min_length=10)
    role: Role
    is_active: bool | None = Field(True, alias='isActive')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateProvider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID = Field(..., alias='practiceId')
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    npi: str = Field(..., max_length=10, min_length=10)
    role: Role
    is_active: bool | None = Field(True, alias='isActive')


class Operatory(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    name: str = Field(..., max_length=100, min_length=1)
    is_active: bool | None = Field(True, alias='isActive')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateOperatory(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID = Field(..., alias='practiceId')
    name: str = Field(..., max_length=100, min_length=1)
    is_active: bool | None = Field(True, alias='isActive')


class Sex(StrEnum):
    male = 'male'
    female = 'female'
    other = 'other'
    unknown = 'unknown'


class Patient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    date_of_birth: date = Field(..., alias='dateOfBirth')
    sex: Sex | None = None
    phone: str | None = Field(None, max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn_last_four: str | None = Field(None, alias='ssnLastFour', max_length=4, min_length=4)
    allergies: list[str] | None = []
    medical_alerts: list[str] | None = Field([], alias='medicalAlerts')
    sms_opt_out: bool | None = Field(False, alias='smsOptOut')
    deleted_at: AwareDatetime | None = Field(None, alias='deletedAt')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreatePatient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID = Field(..., alias='practiceId')
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    date_of_birth: date = Field(..., alias='dateOfBirth')
    sex: Sex | None = None
    phone: str | None = Field(None, max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn_last_four: str | None = Field(None, alias='ssnLastFour', max_length=4, min_length=4)
    allergies: list[str] | None = []
    medical_alerts: list[str] | None = Field([], alias='medicalAlerts')
    sms_opt_out: bool | None = Field(False, alias='smsOptOut')


class UpdatePatient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID | None = Field(None, alias='practiceId')
    first_name: str | None = Field(None, alias='firstName', max_length=100, min_length=1)
    last_name: str | None = Field(None, alias='lastName', max_length=100, min_length=1)
    date_of_birth: date | None = Field(None, alias='dateOfBirth')
    sex: Sex | None = None
    phone: str | None = Field(None, max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn_last_four: str | None = Field(None, alias='ssnLastFour', max_length=4, min_length=4)
    allergies: list[str] | None = []
    medical_alerts: list[str] | None = Field([], alias='medicalAlerts')
    sms_opt_out: bool | None = Field(False, alias='smsOptOut')


class PatientSearchQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    q: str | None = Field(None, min_length=1)
    page: int | None = Field(1, ge=1)
    page_size: int | None = Field(20, alias='pageSize', ge=1, le=100)


class PaginationQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: int | None = Field(1, ge=1)
    page_size: int | None = Field(20, alias='pageSize', ge=1, le=100)


class PaginationMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: int
    page_size: int = Field(..., alias='pageSize')
    total: int
    total_pages: int = Field(..., alias='totalPages')


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    message: str
    details: dict[str, Any] | None = None


class ApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Error
