# generated by datamodel-codegen:
#   filename:  schemas.json
#   timestamp: 2026-04-13T19:04:40+00:00

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, EmailStr, Field, RootModel


class DentalPMSSchemas(RootModel[Any]):
    root: Any = Field(..., title='DentalPMSSchemas')


class Features(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    eligibility_verification: bool | None = False
    copay_estimation: bool | None = False
    claims_submission: bool | None = False


class Practice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    name: str = Field(..., max_length=255, min_length=1)
    timezone: str = Field(..., min_length=1)
    phone: str | None = Field(None, max_length=20)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    features: Features | None = Field({}, validate_default=True)
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreatePractice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., max_length=255, min_length=1)
    timezone: str = Field(..., min_length=1)
    phone: str | None = Field(None, max_length=20)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    features: Features | None = Field({}, validate_default=True)


class Role(StrEnum):
    dentist = 'dentist'
    hygienist = 'hygienist'
    assistant = 'assistant'


class Provider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    npi: str = Field(..., max_length=10, min_length=10)
    role: Role
    is_active: bool | None = Field(True, alias='isActive')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateProvider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID = Field(..., alias='practiceId')
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    npi: str = Field(..., max_length=10, min_length=10)
    role: Role
    is_active: bool | None = Field(True, alias='isActive')


class Operatory(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    name: str = Field(..., max_length=100, min_length=1)
    is_active: bool | None = Field(True, alias='isActive')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateOperatory(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID = Field(..., alias='practiceId')
    name: str = Field(..., max_length=100, min_length=1)
    is_active: bool | None = Field(True, alias='isActive')


class Sex(StrEnum):
    male = 'male'
    female = 'female'
    other = 'other'
    unknown = 'unknown'


class MaritalStatus(StrEnum):
    single = 'single'
    married = 'married'
    divorced = 'divorced'
    widowed = 'widowed'
    separated = 'separated'
    domestic_partner = 'domestic_partner'
    other = 'other'


class Patient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    practice_id: UUID = Field(..., alias='practiceId')
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    date_of_birth: date = Field(..., alias='dateOfBirth')
    sex: Sex | None = None
    marital_status: MaritalStatus | None = Field(None, alias='maritalStatus')
    last_xray_date: date | None = Field(None, alias='lastXrayDate')
    phone: str | None = Field(None, max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn: str | None = Field(None, pattern='^\\d{4}$|^\\d{9}$')
    emergency_contact_name: str | None = Field(None, alias='emergencyContactName', max_length=200)
    emergency_contact_phone: str | None = Field(None, alias='emergencyContactPhone', max_length=20)
    occupation: str | None = Field(None, max_length=200)
    employer: str | None = Field(None, max_length=200)
    referral_source: str | None = Field(None, alias='referralSource', max_length=200)
    allergies: list[str] | None = []
    medical_alerts: list[str] | None = Field([], alias='medicalAlerts')
    medications: list[str] | None = []
    dental_symptoms: list[str] | None = Field([], alias='dentalSymptoms')
    doctor_notes: str | None = Field(None, alias='doctorNotes', max_length=5000)
    sms_opt_out: bool | None = Field(False, alias='smsOptOut')
    deleted_at: AwareDatetime | None = Field(None, alias='deletedAt')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreatePatient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID | None = Field(None, alias='practiceId')
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    date_of_birth: date = Field(..., alias='dateOfBirth')
    sex: Sex | None = None
    marital_status: MaritalStatus | None = Field(None, alias='maritalStatus')
    last_xray_date: date | None = Field(None, alias='lastXrayDate')
    phone: str | None = Field(None, max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn: str | None = Field(None, pattern='^\\d{4}$|^\\d{9}$')
    emergency_contact_name: str | None = Field(None, alias='emergencyContactName', max_length=200)
    emergency_contact_phone: str | None = Field(None, alias='emergencyContactPhone', max_length=20)
    occupation: str | None = Field(None, max_length=200)
    employer: str | None = Field(None, max_length=200)
    referral_source: str | None = Field(None, alias='referralSource', max_length=200)
    allergies: list[str] | None = []
    medical_alerts: list[str] | None = Field([], alias='medicalAlerts')
    medications: list[str] | None = []
    dental_symptoms: list[str] | None = Field([], alias='dentalSymptoms')
    doctor_notes: str | None = Field(None, alias='doctorNotes', max_length=5000)
    sms_opt_out: bool | None = Field(False, alias='smsOptOut')


class UpdatePatient(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_id: UUID | None = Field(None, alias='practiceId')
    first_name: str | None = Field(None, alias='firstName', max_length=100, min_length=1)
    last_name: str | None = Field(None, alias='lastName', max_length=100, min_length=1)
    date_of_birth: date | None = Field(None, alias='dateOfBirth')
    sex: Sex | None = None
    marital_status: MaritalStatus | None = Field(None, alias='maritalStatus')
    last_xray_date: date | None = Field(None, alias='lastXrayDate')
    phone: str | None = Field(None, max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn: str | None = Field(None, pattern='^\\d{4}$|^\\d{9}$')
    emergency_contact_name: str | None = Field(None, alias='emergencyContactName', max_length=200)
    emergency_contact_phone: str | None = Field(None, alias='emergencyContactPhone', max_length=20)
    occupation: str | None = Field(None, max_length=200)
    employer: str | None = Field(None, max_length=200)
    referral_source: str | None = Field(None, alias='referralSource', max_length=200)
    allergies: list[str] | None = []
    medical_alerts: list[str] | None = Field([], alias='medicalAlerts')
    medications: list[str] | None = []
    dental_symptoms: list[str] | None = Field([], alias='dentalSymptoms')
    doctor_notes: str | None = Field(None, alias='doctorNotes', max_length=5000)
    sms_opt_out: bool | None = Field(False, alias='smsOptOut')


class PatientSearchQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    q: str | None = Field(None, min_length=1)
    page: int | None = Field(1, ge=1)
    page_size: int | None = Field(20, alias='pageSize', ge=1, le=100)


class PaginationQuery(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: int | None = Field(1, ge=1)
    page_size: int | None = Field(20, alias='pageSize', ge=1, le=100)


class PaginationMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    page: int
    page_size: int = Field(..., alias='pageSize')
    total: int
    total_pages: int = Field(..., alias='totalPages')


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: str
    message: str
    details: dict[str, Any] | None = None


class ApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: Error


class IntakeFormTokenInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    practice_name: str = Field(..., alias='practiceName')
    patient_first_name: str = Field(..., alias='patientFirstName')


class RelationshipToInsured(StrEnum):
    self = 'self'
    spouse = 'spouse'
    child = 'child'
    other = 'other'


class SubmitIntakeForm(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    date_of_birth: date = Field(..., alias='dateOfBirth')
    sex: Sex | None = None
    phone: str = Field(..., max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn_last_four: str | None = Field(None, alias='ssnLastFour', max_length=4, min_length=4, pattern='^\\d{4}$')
    marital_status: MaritalStatus | None = Field(None, alias='maritalStatus')
    emergency_contact_name: str | None = Field(None, alias='emergencyContactName', max_length=200)
    emergency_contact_phone: str | None = Field(None, alias='emergencyContactPhone', max_length=20)
    occupation: str | None = Field(None, max_length=200)
    employer: str | None = Field(None, max_length=200)
    referral_source: str | None = Field(None, alias='referralSource', max_length=200)
    medical_conditions: list[str] | None = Field([], alias='medicalConditions')
    medications: list[str] | None = []
    allergies: list[str] | None = []
    dental_symptoms: list[str] | None = Field([], alias='dentalSymptoms')
    last_dental_visit: str | None = Field(None, alias='lastDentalVisit')
    last_xray_date: str | None = Field(None, alias='lastXrayDate')
    previous_dentist: str | None = Field(None, alias='previousDentist')
    chief_complaint: str | None = Field(None, alias='chiefComplaint')
    insurance_carrier: str | None = Field(None, alias='insuranceCarrier')
    insurance_member_id: str | None = Field(None, alias='insuranceMemberId')
    insurance_group_number: str | None = Field(None, alias='insuranceGroupNumber')
    insurance_holder_name: str | None = Field(None, alias='insuranceHolderName')
    insurance_holder_dob: str | None = Field(None, alias='insuranceHolderDob')
    relationship_to_insured: RelationshipToInsured | None = Field(None, alias='relationshipToInsured')
    hipaa_consent_accepted: bool = Field(..., alias='hipaaConsentAccepted')
    hipaa_consent_timestamp: AwareDatetime = Field(..., alias='hipaaConsentTimestamp')
    hipaa_consent_signature: str = Field(..., alias='hipaaConsentSignature', min_length=1)
    sms_opt_in: bool = Field(..., alias='smsOptIn')


class SendIntakeForm(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    patient_id: UUID = Field(..., alias='patientId')


class SendIntakeFormResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    intake_form_id: UUID = Field(..., alias='intakeFormId')
    expires_at: AwareDatetime = Field(..., alias='expiresAt')
    form_url: AnyUrl = Field(..., alias='formUrl')


class Status(StrEnum):
    pending = 'pending'
    completed = 'completed'
    expired = 'expired'


class IntakeFormSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    patient_id: UUID = Field(..., alias='patientId')
    status: Status
    expires_at: AwareDatetime = Field(..., alias='expiresAt')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    created_by: UUID = Field(..., alias='createdBy')


class Responses(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    first_name: str = Field(..., alias='firstName', max_length=100, min_length=1)
    last_name: str = Field(..., alias='lastName', max_length=100, min_length=1)
    date_of_birth: date = Field(..., alias='dateOfBirth')
    sex: Sex | None = None
    phone: str = Field(..., max_length=20)
    email: EmailStr | None = Field(None, max_length=255)
    address_line1: str | None = Field(None, alias='addressLine1', max_length=255)
    address_line2: str | None = Field(None, alias='addressLine2', max_length=255)
    city: str | None = Field(None, max_length=100)
    state: str | None = Field(None, max_length=2, min_length=2)
    zip: str | None = Field(None, max_length=10)
    ssn_last_four: str | None = Field(None, alias='ssnLastFour', max_length=4, min_length=4, pattern='^\\d{4}$')
    marital_status: MaritalStatus | None = Field(None, alias='maritalStatus')
    emergency_contact_name: str | None = Field(None, alias='emergencyContactName', max_length=200)
    emergency_contact_phone: str | None = Field(None, alias='emergencyContactPhone', max_length=20)
    occupation: str | None = Field(None, max_length=200)
    employer: str | None = Field(None, max_length=200)
    referral_source: str | None = Field(None, alias='referralSource', max_length=200)
    medical_conditions: list[str] | None = Field([], alias='medicalConditions')
    medications: list[str] | None = []
    allergies: list[str] | None = []
    dental_symptoms: list[str] | None = Field([], alias='dentalSymptoms')
    last_dental_visit: str | None = Field(None, alias='lastDentalVisit')
    last_xray_date: str | None = Field(None, alias='lastXrayDate')
    previous_dentist: str | None = Field(None, alias='previousDentist')
    chief_complaint: str | None = Field(None, alias='chiefComplaint')
    insurance_carrier: str | None = Field(None, alias='insuranceCarrier')
    insurance_member_id: str | None = Field(None, alias='insuranceMemberId')
    insurance_group_number: str | None = Field(None, alias='insuranceGroupNumber')
    insurance_holder_name: str | None = Field(None, alias='insuranceHolderName')
    insurance_holder_dob: str | None = Field(None, alias='insuranceHolderDob')
    relationship_to_insured: RelationshipToInsured | None = Field(None, alias='relationshipToInsured')
    hipaa_consent_accepted: bool = Field(..., alias='hipaaConsentAccepted')
    hipaa_consent_timestamp: AwareDatetime = Field(..., alias='hipaaConsentTimestamp')
    hipaa_consent_signature: str = Field(..., alias='hipaaConsentSignature', min_length=1)
    sms_opt_in: bool = Field(..., alias='smsOptIn')


class IntakeFormDetail(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    patient_id: UUID = Field(..., alias='patientId')
    status: Status
    expires_at: AwareDatetime = Field(..., alias='expiresAt')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    created_by: UUID = Field(..., alias='createdBy')
    responses: Responses | None


class Priority(StrEnum):
    primary = 'primary'
    secondary = 'secondary'


class Insurance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    patient_id: UUID = Field(..., alias='patientId')
    practice_id: UUID = Field(..., alias='practiceId')
    priority: Priority | None = 'primary'
    carrier: str = Field(..., max_length=255, min_length=1)
    member_id: str | None = Field(None, alias='memberId', max_length=100)
    group_number: str | None = Field(None, alias='groupNumber', max_length=100)
    relationship_to_insured: RelationshipToInsured | None = Field('self', alias='relationshipToInsured')
    insured_first_name: str | None = Field(None, alias='insuredFirstName', max_length=100)
    insured_last_name: str | None = Field(None, alias='insuredLastName', max_length=100)
    insured_date_of_birth: date | None = Field(None, alias='insuredDateOfBirth')
    is_active: bool | None = Field(True, alias='isActive')
    created_at: AwareDatetime = Field(..., alias='createdAt')
    updated_at: AwareDatetime = Field(..., alias='updatedAt')


class CreateInsurance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    priority: Priority | None = 'primary'
    carrier: str = Field(..., max_length=255, min_length=1)
    member_id: str | None = Field(None, alias='memberId', max_length=100)
    group_number: str | None = Field(None, alias='groupNumber', max_length=100)
    relationship_to_insured: RelationshipToInsured | None = Field('self', alias='relationshipToInsured')
    insured_first_name: str | None = Field(None, alias='insuredFirstName', max_length=100)
    insured_last_name: str | None = Field(None, alias='insuredLastName', max_length=100)
    insured_date_of_birth: date | None = Field(None, alias='insuredDateOfBirth')


class UpdateInsurance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    priority: Priority | None = 'primary'
    carrier: str | None = Field(None, max_length=255, min_length=1)
    member_id: str | None = Field(None, alias='memberId', max_length=100)
    group_number: str | None = Field(None, alias='groupNumber', max_length=100)
    relationship_to_insured: RelationshipToInsured | None = Field('self', alias='relationshipToInsured')
    insured_first_name: str | None = Field(None, alias='insuredFirstName', max_length=100)
    insured_last_name: str | None = Field(None, alias='insuredLastName', max_length=100)
    insured_date_of_birth: date | None = Field(None, alias='insuredDateOfBirth')
